src/VR/AppBundle/Entity/Error.php
<?php

namespace VR\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Error
 *
 * @author Michał Jabłoński <mjapko@gmail.com>
 *
 * @ORM\Entity(repositoryClass="VR\AppBundle\Entity\Repository\ErrorRepository")
 * @ORM\Table(name="errors")
 */
class Error
{
    const STATUS_NEW = 'New';
    const STATUS_READY = 'Ready';
    const STATUS_IN_PROGRESS = 'In progress';
    const STATUS_ERROR = 'Error';
    const STATUS_DONE = 'Done';

	/**
	 * @ORM\Id
	 * @ORM\Column(type="bigint")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Message", inversedBy="errors")
     * @ORM\JoinColumn(name="message_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $message;

    /**
     * @ORM\Column(name="step_no", type="bigint")
     */
    protected $stepNo;

	/**
	 * @ORM\Column(name="error_message", type="text")
	 */
	protected $errorMessage;

    /**
     * @ORM\Column(name="entry_ts", type="datetime")
     */
    protected $entryAt;

    /**
     * @ORM\Column(name="error_payload", type="text", nullable=true)
     */
    protected $errorPayload;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set errorMessage
     *
     * @param string $errorMessage
     * @return Error
     */
    public function setErrorMessage($errorMessage)
    {
        $this->errorMessage = $errorMessage;

        return $this;
    }

    /**
     * Get errorMessage
     *
     * @return string 
     */
    public function getErrorMessage()
    {
        return $this->errorMessage;
    }

    /**
     * Set entryAt
     *
     * @param \DateTime $entryAt
     * @return Error
     */
    public function setEntryAt($entryAt)
    {
        $this->entryAt = $entryAt;

        return $this;
    }

    /**
     * Get entryAt
     *
     * @return \DateTime 
     */
    public function getEntryAt()
    {
        return $this->entryAt;
    }

    /**
     * Set message
     *
     * @param \VR\AppBundle\Entity\Message $message
     * @return Error
     */
    public function setMessage(\VR\AppBundle\Entity\Message $message = null)
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Get message
     *
     * @return \VR\AppBundle\Entity\Message 
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @return mixed
     */
    public function getStepNo()
    {
        return $this->stepNo;
    }

    /**
     * @param mixed $stepNo
     *
     * @return $this
     */
    public function setStepNo($stepNo)
    {
        $this->stepNo = $stepNo;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getErrorPayload()
    {
        return $this->errorPayload;
    }

    /**
     * @param mixed $errorPayload
     *
     * @return $this
     */
    public function setErrorPayload($errorPayload)
    {
        $this->errorPayload = $errorPayload;

        return $this;
    }

    public function getErrorPayloadIds()
    {
        $payload = json_decode($this->getErrorPayload(), true);

        if (!$payload) return [];

        # legacy - for old payloads without "module" key
        $items = isset($payload['ids']) ? $payload['ids'] : $payload;

        $ids = [];

        if (count($items)) {
            foreach ($items as $item) {
                $ids[] = $item['id'];
            }
        }

        return $ids;
    }

    public function getErrorPayloadModule()
    {
        $payload = json_decode($this->getErrorPayload(), true);

        if (!$payload) return [];

        return isset($payload['module']) ? $payload['module'] : null;
    }

    public function getShowCreateNew()
    {
        $payload = json_decode($this->getErrorPayload(), true);

        if (!$payload) return true;

        return isset($payload['showCreateNew']) ? $payload['showCreateNew'] : true;
    }

    public function getShowUseThis()
    {
        $payload = json_decode($this->getErrorPayload(), true);

        if (!$payload) return true;

        return isset($payload['showUseThis']) ? $payload['showUseThis'] : true;
    }

    public function getShowButtons()
    {
        $payload = json_decode($this->getErrorPayload(), true);

        if (!$payload) return true;

        return isset($payload['showButtons']) ? $payload['showButtons'] : true;
    }

    public function getShowRadioButtons()
    {
        $payload = json_decode($this->getErrorPayload(), true);

        if (!$payload) return true;

        return isset($payload['showRadioButtons']) ? $payload['showRadioButtons'] : true;
    }
}

src/VR/AppBundle/Entity/Message.php
<?php

namespace VR\AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Message
 *
 * @author Michał Jabłoński <mjapko@gmail.com>
 * @author Jimmie Louis Borch
 *
 * @ORM\Entity(repositoryClass="VR\AppBundle\Entity\Repository\MessageRepository")
 * @ORM\Table(name="messages", indexes={
 *     @ORM\Index(name="md5_index", columns={"unique_md5"}),
 *     @ORM\Index(name="message_type", columns={"message_type"}),
 *     @ORM\Index(name="message_status", columns={"message_status"}),
 *     @ORM\Index(name="forced", columns={"forced"}),
 *     @ORM\Index(name="run_at", columns={"run_at"}),
 * })
 * @ORM\HasLifecycleCallbacks
 */
class Message
{
    const STATUS_NEW = 'New';
    const STATUS_IN_PROGRESS = 'In progress';
    const STATUS_RERUN = 'Rerun';
    const STATUS_ERROR = 'Error';
    const STATUS_FINISHED = 'Finished';
    const STATUS_CANCELLED = 'Cancelled';
    const STATUS_HALTED = 'Halted';

    public static $allowedStatuses = [
        self::STATUS_NEW,
        self::STATUS_IN_PROGRESS,
        self::STATUS_RERUN,
        self::STATUS_ERROR,
        self::STATUS_FINISHED,
        self::STATUS_CANCELLED,
        self::STATUS_HALTED
    ];

    public static $completedStatuses = [
        'Done',
        'Completed',
        'Finished',
    ];

	/**
	 * @ORM\Id
	 * @ORM\Column(type="bigint")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * @ORM\Column(name="message_created", type="datetime")
	 */
	protected $flowCreatedAt;

    /**
     * Contains JSON with information about all steps.
     *
     * @ORM\Column(name="message_steps", type="text")
     */
    protected $flow;

    public $prettyFlowLastError;

    /**
     * @ORM\Column(name="message_type", type="string", length=255)
     */
    protected $flowName;

    /**
     * @ORM\Column(name="message_status", type="string", length=25)
     */
    protected $flowStatus;

    /**
     * @ORM\Column(name="message_payload", type="text")
     */
    protected $flowMessage;

    public $prettyFlowMessageLastError;

    /**
     * @ORM\OneToMany(targetEntity="Error", mappedBy="message")
     * @ORM\OrderBy({"entryAt" = "DESC"})
     */
    protected $errors;

    /**
     * @ORM\OneToMany(targetEntity="StepChange", mappedBy="message")
     */
    protected $stepChanges;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $forced;

    /**
     * @ORM\Column(name="run_at", type="datetime", nullable=true)
     */
    protected $runAt;

    /**
     * @ORM\Column(name="unique_md5", unique=true)
     */
    protected $md5;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->forced = false;
        $this->setFlowCreatedAt(new \DateTime());

        $this->errors = new \Doctrine\Common\Collections\ArrayCollection();
        $this->stepChanges = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function generateMd5()
    {
        if (!$this->md5) {
            $this->md5 = md5($this->flow . $this->flowMessage . $this->flowName);
        }
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set flowCreatedAt
     *
     * @param \DateTime $flowCreatedAt
     * @return Message
     */
    public function setFlowCreatedAt($flowCreatedAt)
    {
        $this->flowCreatedAt = $flowCreatedAt;

        return $this;
    }

    /**
     * Get flowCreatedAt
     *
     * @return \DateTime 
     */
    public function getFlowCreatedAt()
    {
        return $this->flowCreatedAt;
    }

    /**
     * Set flow
     *
     * @param string $steps
     * @return Message
     */
    public function setFlow($steps)
    {
        $this->flow = $steps;

        return $this;
    }

    /**
     * Get flow
     *
     * @return string 
     */
    public function getFlow()
    {
        return $this->flow;
    }

    public function getStepsArray()
    {
        $parsedJson = json_decode($this->flow, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new \Exception('Steps JSON parsing error: ' . json_last_error_msg());
        }

        return $parsedJson;
    }

    public function getPrettyFlow()
    {
        $json = json_decode($this->flow, true);

        $this->prettyFlowLastError = json_last_error_msg();

        if (!$json) return null;

        return json_encode($json, JSON_PRETTY_PRINT);
    }

    /**
     * Set flowStatus
     *
     * @param integer $flowStatus
     * @return Message
     */
    public function setFlowStatus($flowStatus)
    {
        $this->flowStatus = $flowStatus;

        return $this;
    }

    /**
     * Get flowStatus
     *
     * @return integer 
     */
    public function getFlowStatus()
    {
        return $this->flowStatus;
    }

    public function isStatus($statusName)
    {
        return strtolower($this->flowStatus) == strtolower($statusName);
    }

    public function getFlowStatusCssClass()
    {
        $cssClasses = [
            'Error' => 'label-danger',
            'In progress' => 'label-primary',
            'Halted' => 'label-warning'
        ];

        return isset($cssClasses[$this->flowStatus]) ? $cssClasses[$this->flowStatus] : 'label-default';
    }

    /**
     * Set flowMessage
     *
     * @param string $payload
     * @return Message
     */
    public function setFlowMessage($payload)
    {
        $this->flowMessage = $payload;

        return $this;
    }

    /**
     * Get flowMessage
     *
     * @return string 
     */
    public function getFlowMessage()
    {
        return $this->flowMessage;
    }

    public function getPayloadArray()
    {
        return json_decode($this->flowMessage, true);
    }

    public function setPayloadArray($array)
    {
        $this->flowMessage = json_encode($array);
    }

    public function getPrettyFlowMessage()
    {
        $json = json_decode($this->flowMessage, true);

        $this->prettyFlowMessageLastError = json_last_error_msg();

        if (!$json) return null;

        $json = json_encode($json, JSON_PRETTY_PRINT);

        return $json;
    }

    /**
     * Add errors
     *
     * @param \VR\AppBundle\Entity\Error $errors
     * @return Message
     */
    public function addError(\VR\AppBundle\Entity\Error $errors)
    {
        $this->errors[] = $errors;

        return $this;
    }

    /**
     * Remove errors
     *
     * @param \VR\AppBundle\Entity\Error $errors
     */
    public function removeError(\VR\AppBundle\Entity\Error $errors)
    {
        $this->errors->removeElement($errors);
    }

    /**
     * Get errors
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getErrors()
    {
        return $this->errors;
    }

    public function getErrorsForStep($stepNumber)
    {
        $errors = new ArrayCollection();

        if (count($this->errors)) {
            foreach ($this->errors as $error) {
                if ($error->getStepNo() == $stepNumber) {
                    $errors[] = $error;
                }
            }
        }

        return $errors;
    }

    /**
     * @return mixed
     */
    public function getFlowName()
    {
        return $this->flowName;
    }

    /**
     * @param mixed $messageType
     */
    public function setFlowName($messageType)
    {
        $this->flowName = $messageType;
    }

    /**
     * @return mixed
     */
    public function getStepChanges()
    {
        return $this->stepChanges;
    }

    public function changeStepStatus($stepNumber, $newStatus)
    {
        $this->changeStepParameter($stepNumber, 'Status', $newStatus);

        return $this;
    }

    public function changeStepParameter($stepNumber, $parameter, $value)
    {
        $steps = json_decode($this->flow, true);

        if (isset($steps[$stepNumber])) {
            $steps[$stepNumber][$parameter] = $value;
        } else {
            throw new \Exception('Step with number ' . $stepNumber . ' not found.');
        }

        $this->flow = json_encode($steps);

        return $this;
    }

    public function batchChangeStepStatuses($from, $to)
    {
        $steps = json_decode($this->flow, true);

        if (count($steps)) {
            foreach ($steps as $stepNumber => $stepData) {
                if (strtolower($stepData['Status']) == strtolower($from) || $from === null) {
                    $steps[$stepNumber]['Status'] = $to;
                }
            }
        }

        $this->flow = json_encode($steps);

        return $this;
    }

    public function resetGuids()
    {
        $steps = json_decode($this->flow, true);

        if (count($steps)) {
            foreach ($steps as $stepNumber => $stepData) {
                $steps[$stepNumber]['GUID'] = '';
            }
        }

        $this->flow = json_encode($steps);
    }

    public function isActionAllowed($actionName)
    {
        switch ($actionName) {
            case 'run':
                return !in_array(strtolower($this->getFlowStatus()), ['in progress', 'finished', 'cancelled']);
            case 'new':
                return !in_array(strtolower($this->getFlowStatus()), ['finished', 'new']);
            case 'halt':
                return !in_array(strtolower($this->getFlowStatus()), ['finished', 'halted', 'cancelled']);
            case 'cancel':
                return !in_array(strtolower($this->getFlowStatus()), ['finished', 'cancelled']);
            case 'reset_guids':
                return !in_array(strtolower($this->getFlowStatus()), ['finished']);
            default:
                throw new \InvalidArgumentException('This action name is not allowed.');
        }
    }

    /**
     * Add stepChanges
     *
     * @param \VR\AppBundle\Entity\StepChange $stepChanges
     * @return Message
     */

src/VR/AppBundle/Resources/views/Message/ajax_status_box.html.twig
<table class="table table-striped table-condensed-max table-hover">
    {% for status, counter in statusCounters %}
        <tr>
            <td class="col-md-1">
                {{ status }}
            </td>
            <td class="col-md-1" style="text-align: right">
                {{ counter|number_format(0, ',', '.') }}
            </td>
        </tr>
    {% endfor %}
</table>

src/VR/AppBundle/Resources/views/Message/changes.html.twig
<table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
        <th>Changed</th>
        <th>Message status before</th>
        <th>Message status after</th>
        <th>Step number</th>
    </tr>
    </thead>
    <tbody>
    {% for change in stepChanges %}
        <tr>
            <td style="text-align: center; vertical-align: middle">
                <span class="label label-info">
                    {{ change.changedAt|date('Y-m-d H:i:s') }}
                </span>
            </td>
            <td>
                {{ change.messageStatusBefore }}
            </td>
            <td>
                {{ change.messageStatusAfter }}
            </td>
            <td>
                {{ change.stepNumber }}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

src/VR/AppBundle/Resources/views/Message/list.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Messages</h1>

    <div class="row">
        <div class="col-md-6">
            {% include 'VRAppBundle:Message:search.html.twig' %}
        </div>
        <div class="col-md-6">
            {% include 'VRAppBundle:Message:status.html.twig' %}
        </div>
    </div>

    <form action="{{ path('message_batch') }}" id="batch" name="batch" method="post">
        <table id="results" class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <th>
                    <input type="checkbox" class="checkbox-select-all" />
                </th>
                <th>
                    {{ knp_pagination_sortable(entities, 'ID', 'm.id') }}

                    {% if entities.isSorted('m.id') %}
                        <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
                    {% endif %}
                </th>
                <th>
                    {{ knp_pagination_sortable(entities, 'Created', 'm.flowCreatedAt') }}

                    {% if entities.isSorted('m.flowCreatedAt') %}
                        <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
                    {% endif %}
                </th>
                <th>
                    {{ knp_pagination_sortable(entities, 'Type', 'm.flowName') }}

                    {% if entities.isSorted('m.flowName') %}
                        <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
                    {% endif %}
                </th>
                <th>
                    {{ knp_pagination_sortable(entities, 'Run at', 'm.runAt') }}

                    {% if entities.isSorted('m.runAt') %}
                        <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
                    {% endif %}
                </th>
                <th>
                    {{ knp_pagination_sortable(entities, 'Status', 'm.flowStatus') }}

                    {% if entities.isSorted('m.flowStatus') %}
                        <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
                    {% endif %}
                </th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for entity in entities %}
                {% include 'VRAppBundle:Message:list_item.html.twig' %}
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td colspan="7">
                    {% include 'VRAppBundle:Message:list_batch_actions.html.twig' %}

                    <div class="pull-right">
                        <span class="label label-default">
                            Results: {{ entities.paginationData.totalCount|number_format(0, ',', '.') }}
                        </span>
                    </div>
                </td>
            </tr>
            </tfoot>
        </table>

        <input type="hidden" name="action" value="" />
        <input type="hidden" name="action_type" value="" />
    </form>

    <div>
        <div class="navigation pull-left">
            {{ knp_pagination_render(entities) }}
        </div>

        <div class="pull-right">
            {% for itemsNumber in [10, 50, 100, 200, 500] %}
                <a href="?items={{ itemsNumber }}" class="btn btn-xs {% if itemsPerPage == itemsNumber %}btn-primary{% else %}btn-default{% endif %}" title="Items per page: {{ itemsNumber }}">
                    {{ itemsNumber }}
                </a>
            {% endfor %}
        </div>

        <div class="clearfix"></div>
    </div>

{% endblock %}

src/VR/AppBundle/Resources/views/Message/list_item.html.twig
<tr class="status-{{ entity.flowStatus|lower }}">
    <td>
        <input type="checkbox" id="batch_{{ loop.index }}" name="batch_ids[]" value="{{ entity.id }}" class="checkbox-select-all-item" />
    </td>
    <td>{{ entity.id }}</td>
    <td>{% if entity.flowCreatedAt %}{{ entity.flowCreatedAt|date('Y-m-d H:i:s') }}{% endif %}</td>
    <td>
        {% if messageTypes[entity.flowName] is defined %}
            {{ messageTypes[entity.flowName] }}
        {% endif %}
    </td>
    <td>
        {% if entity.runAt %}
            {{ entity.runAt|date('Y-m-d H:i:s') }}
        {% endif %}
    </td>
    <td class="ajax-reload2" data-url="{{ path('message_ajax_list_status', {'id': entity.id}) }}" data-interval="30">
                        <span class="label {{ entity.flowStatusCssClass }}">
                            {{ entity.flowStatus }}
                        </span>
    </td>
    <td class="ajax-reload2" data-url="{{ path('message_ajax_list_actions', {'id': entity.id}) }}" data-interval="30">
        {% include 'VRAppBundle:Message:list_actions.html.twig' %}
    </td>
</tr>

src/VR/AppBundle/Resources/views/Message/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Message</h1>

    <p>
        {% include 'VRAppBundle:Message:show_actions.html.twig' %}
    </p>

    <div class="clearfix" style="margin-bottom: 10px"></div>

    <table class="table table-bordered table-striped table-hover">
        <tbody>
        <tr>
            <th class="col-md-2">ID</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>
                {% if messageTypes[entity.flowName] is defined %}
                    {{ messageTypes[entity.flowName] }}
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Created</th>
            <td>{{ entity.flowCreatedAt|date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <th>Message steps</th>
            <td>
                <a href="#" class="btn btn-default btn-xs switch switch-animate" data-target=".entity-flow">
                    <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                    show/hide
                </a>

                <div class="entity-flow collapsed">
                    <pre>{{ entity.prettyFlow }}</pre>

                    {% if entity.prettyFlowLastError and entity.prettyFlowLastError != 'No error' %}
                        <div class="alert alert-danger">
                            JSON parsing error: {{ entity.prettyFlowLastError }}
                        </div>
                    {% endif %}
                </div>
            </td>
        </tr>
        <tr>
            <th>Message status</th>
            <td>
                <span class="label {{ entity.flowStatusCssClass }}">
                    {{ entity.flowStatus }}
                </span>
            </td>
        </tr>
        <tr>
            <th>Message</th>
            <td>
                <a href="#" class="btn btn-default btn-xs switch switch-animate" data-target=".entity-flow-message">
                    <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                    show/hide
                </a>

                <div class="entity-flow-message collapsed">
                    <pre>{{ entity.prettyFlowMessage }}</pre>

                    {% if entity.prettyFlowMessageLastError and entity.prettyFlowMessageLastError != 'No error' %}
                        <div class="alert alert-danger">
                            JSON parsing error: {{ entity.prettyFlowMessageLastError }}
                        </div>
                    {% endif %}
                </div>
            </td>
        </tr>
        <tr>
            <th>Completed steps</th>
            <td>
                <div class="progress">
                    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="{{ completedStepsPercentage }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ completedStepsPercentage }}%;">
                        {{ completedStepsPercentage }}% ({{ countCompletedSteps }}/{{ countAllSteps }} done)
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <th>Run at</th>
            <td>
                {% if entity.isStatus('new') %}
                    {% include 'VRAppBundle:Message:show_run_at.html.twig' %}
                {% else %}
                    {% if entity.runAt %}
                        {{ entity.runAt|date('Y-m-d H:i:s') }}
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>

    <p>
        <ul class="nav nav-tabs" data-tabs="tabs">
            <li role="presentation" class="active">
                <a href="#message-steps" data-toggle="tab">Message steps</a>
            </li>
            <li role="presentation">
                <a href="#message-changes" data-toggle="tab">Step changes</a>
            </li>
        </ul>
    </p>

    <div class="tab-content">
        <div class="tab-pane active" id="message-steps">
            {% include 'VRAppBundle:Message:steps.html.twig' %}
        </div>
        <div class="tab-pane" id="message-changes">
            {% include 'VRAppBundle:Message:changes.html.twig' %}
        </div>
    </div>
{% endblock %}

src/VR/AppBundle/Resources/views/Message/show_run_at.html.twig
<form action="" method="post" class="form-inline">
    {{ form_errors(runAtForm) }}

    <div class="form-group">
        {{ form_widget(runAtForm.runAt) }}
        {{ form_errors(runAtForm.runAt) }}
    </div>

    {{ form_rest(runAtForm) }}

    <button type="submit" class="btn btn-small btn-default">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Set
    </button>
</form>

src/VR/AppBundle/Resources/views/Message/step_errors.html.twig
{% if entity.errorsForStep(stepNumber).count %}
    <table class="table table-bordered table-striped step-{{ stepNumber }}-errors {% if stepData.Status != 'Error' %}collapsed{% endif %}">
        <thead>
        <tr>
            <th class="col-md-1">ID</th>
            <th>Message</th>
            <th class="col-md-3">Entry at</th>
        </tr>
        </thead>
        <tbody>
        {% for error in entity.errorsForStep(stepNumber) %}
            <tr{% if not loop.first %} class="disabled"{% endif %}>
                <td>
                    {{ error.id }}
                </td>
                <td>
                    <p>
                        {{ error.errorMessage }}
                    </p>

                    {% if error.errorPayload and loop.first %}
                        <form action="{{ path('message_set_step_guid', {id: entity.id, stepNumber: stepNumber}) }}" method="post">
                            <ul class="list-group">
                                {% for id in error.errorPayloadIds %}
                                    <li class="list-group-item {% if stepData.GUID == id %}active{% endif %}">
                                        {% if error.showRadioButtons %}
                                            <input type="radio" name="guid" value="{{ id }}" {% if stepData.GUID == id %}checked="checked"{% endif %} />
                                        {% endif %}

                                        GUID {{ loop.index }}:

                                        {% if error.errorPayloadModule %}
                                            <a href="{{ sugarcrmUrl|replace({'{module}': error.errorPayloadModule, '{guid}': id}) }}" target="_blank" style="{% if stepData.GUID == id %}color:white{% endif %}">
                                                {{ id }}
                                            </a>
                                        {% elseif stepData.Module %}
                                            <a href="{{ sugarcrmUrl|replace({'{module}': stepData.Module, '{guid}': id}) }}" target="_blank" style="{% if stepData.GUID == id %}color:white{% endif %}">
                                                {{ id }}
                                            </a>
                                        {% else %}
                                            {{ id }}
                                        {% endif %}
                                    </li>
                                {% endfor %}

                                {% if error.showCreateNew %}
                                    <li class="list-group-item {% if stepData.GUID == 'new-record' %}active{% endif %}">
                                        <input type="radio" name="guid" value="new-record" {% if stepData.GUID == 'new-record' %}checked="checked"{% endif %} />
                                        Create new record
                                    </li>
                                {% endif %}

                                {% if error.showUseThis %}
                                    <li class="list-group-item">
                                        <input type="radio" name="guid" value="new-guid" />
                                        Use this GUID:
                                        <input type="text" name="new-guid-value" placeholder="XXXX-XXXX-XXXX-XXXX" size="25" />
                                    </li>
                                {% endif %}

                                {% if error.showButtons %}
                                    <li class="list-group-item">
                                        <button type="submit" class="btn btn-xs btn-success">
                                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Confirm and set message status New
                                        </button>
                                    </li>
                                {% endif %}
                            </ul>
                        </form>
                    {% endif %}
                </td>
                <td>
                    {{ error.entryAt|date('Y-m-d H:i:s') }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}