src/VR/AppBundle/Entity/ProcessSchedule.php
<?php

namespace VR\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use VR\AppBundle\Plugin\PluginManager;
use VR\AppBundle\Service\CronHelper;

/**
 * @author Michał Jabłoński <mjapko@gmail.com>
 * @author Andrzej Prusinowski <andrzej@avris.it>
 *
 * @ORM\Entity(repositoryClass="VR\AppBundle\Entity\Repository\ProcessScheduleRepository")
 * @ORM\Table(name="process_schedules")
 */
class ProcessSchedule
{
    public static $sqlTypes = [
        'collector.sql.main',
        'collector.sql.Duplet'
    ];

	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

    /**
     * @ORM\Column(type="string", nullable=true, length=25)
     * @Assert\NotBlank(message="'Day of Week' value should not be blank.")
     * @Assert\Regex(pattern="/^[-0-9,\/*$]+/", message="'Day of Week' value is not valid.")
     */
    protected $dayOfWeek;

    /**
     * @ORM\Column(type="string", nullable=true, length=25)
     * @Assert\NotBlank(message="'Month' value should not be blank.")
     * @Assert\Regex(pattern="/^[-0-9,\/*$]+/", message="'Month' value is not valid.")
     */
    protected $month;

    /**
     * @ORM\Column(type="string", nullable=true, length=25)
     * @Assert\NotBlank(message="'Day of Month' value should not be blank.")
     * @Assert\Regex(pattern="/^[-0-9,\/*$]+/", message="'Day of Month' value is not valid.")
     */
    protected $dayOfMonth;

    /**
     * @ORM\Column(type="string", nullable=true, length=25)
     * @Assert\NotBlank(message="'Hour' value should not be blank.")
     * @Assert\Regex(pattern="/^[-0-9,\/*$]+/", message="'Hour' value is not valid.")
     */
    protected $hour;

    /**
     * @ORM\Column(type="string", nullable=true, length=25)
     * @Assert\NotBlank(message="'Minute' value should not be blank.")
     * @Assert\Regex(pattern="/^[-0-9,\/*$]+/", message="'Minute' value is not valid.")
     */
    protected $minute;

    /**
     * @ORM\Column(type="string", length=127)
     */
    protected $type;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $parameters;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $lastRunAt;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $enabled;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->enabled = true;

        $this->minute = '*';
        $this->hour = '*';
        $this->dayOfMonth = '*';
        $this->month = '*';
        $this->dayOfWeek = '*';
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dayOfWeek
     *
     * @param string $dayOfWeek
     * @return ProcessSchedule
     */
    public function setDayOfWeek($dayOfWeek)
    {
        $this->dayOfWeek = $dayOfWeek;

        return $this;
    }

    /**
     * Get dayOfWeek
     *
     * @return string
     */
    public function getDayOfWeek()
    {
        return $this->dayOfWeek;
    }

    /**
     * Set month
     *
     * @param string $month
     * @return ProcessSchedule
     */
    public function setMonth($month)
    {
        $this->month = $month;

        return $this;
    }

    /**
     * Get month
     *
     * @return string
     */
    public function getMonth()
    {
        return $this->month;
    }

    /**
     * Set dayOfMonth
     *
     * @param string $dayOfMonth
     * @return ProcessSchedule
     */
    public function setDayOfMonth($dayOfMonth)
    {
        $this->dayOfMonth = $dayOfMonth;

        return $this;
    }

    /**
     * Get dayOfMonth
     *
     * @return string
     */
    public function getDayOfMonth()
    {
        return $this->dayOfMonth;
    }

    /**
     * Set hour
     *
     * @param string $hour
     * @return ProcessSchedule
     */
    public function setHour($hour)
    {
        $this->hour = $hour;

        return $this;
    }

    /**
     * Get hour
     *
     * @return string
     */
    public function getHour()
    {
        return $this->hour;
    }

    /**
     * Set minute
     *
     * @param string $minute
     * @return ProcessSchedule
     */
    public function setMinute($minute)
    {
        $this->minute = $minute;

        return $this;
    }

    /**
     * Get minute
     *
     * @return string
     */
    public function getMinute()
    {
        return $this->minute;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return ProcessSchedule
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set parameters
     *
     * @param string $parameters
     * @return ProcessSchedule
     */
    public function setParameters($parameters)
    {
        if (in_array($this->getType(), self::$sqlTypes)) {
            $this->parameters = json_encode(['sql' => $parameters]);
        } else {
            $this->parameters = $parameters;
        }

        return $this;
    }

    /**
     * Get parameters
     *
     * @return string 
     */
    public function getParameters($pure = false)
    {
        if (in_array($this->getType(), self::$sqlTypes) && !$pure) {
            $parameters = json_decode($this->parameters, true);
            return $parameters['sql'];
        } else {
            return $this->parameters;
        }
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return ProcessSchedule
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function canBeRunAt(\DateTime $dateTime)
    {
        return (
            (in_array((int) $dateTime->format('w'), CronHelper::getCronPossibilities($this->dayOfWeek))) &&
            (in_array((int) $dateTime->format('n'), CronHelper::getCronPossibilities($this->month))) &&
            (in_array((int) $dateTime->format('j'), CronHelper::getCronPossibilities($this->dayOfMonth))) &&
            (in_array((int) $dateTime->format('G'), CronHelper::getCronPossibilities($this->hour))) &&
            (in_array((int) $dateTime->format('i'), CronHelper::getCronPossibilities($this->minute)))
        );
    }

    public function getTime()
    {
        return trim($this->minute . ' ' . $this->hour . ' ' . $this->dayOfMonth . ' ' . $this->month . ' ' . $this->dayOfWeek);
    }

    public function getTypeName()
    {
        return isset(PluginManager::$runModeNames[$this->getType()]) ? PluginManager::$runModeNames[$this->getType()] : null;
    }

    /**
     * @Assert\Callback
     */
    public function validateParameters(ExecutionContextInterface $context)
    {
        if (!in_array($this->getType(), self::$sqlTypes) && $this->getParameters(true) && !$this->checkParametersJsonStructure()) {
            $context->buildViolation('Provided JSON structure is not valid.')
                ->atPath('parameters')
                ->addViolation();
        }

        $parameters = $this->getParametersArray();

        //@todo: check parameters provided by plugins
//        if (isset(ProcessManager::$processTypeParameters[$this->getType()])) {
//            $parameterSchema = ProcessManager::$processTypeParameters[$this->getType()];
//            foreach ($parameterSchema as $name => $value) {
//                if ($value['required'] && !isset($parameters[$name])) {
//                    $context->buildViolation(sprintf('Please provide %s parameter.', $name))
//                        ->atPath('parameters')
//                        ->addViolation();
//                }
//            }
//        }
    }

    protected function checkParametersJsonStructure()
    {
        json_decode($this->getParameters(true));

        return (json_last_error() !== JSON_ERROR_NONE) ? false : true;
    }

    public function getParametersArray()
    {
        if (in_array($this->getType(), self::$sqlTypes)) {
            return ['sql' => $this->parameters];
        }

        return $this->getParameters() ? json_decode($this->getParameters(true), true) : [];
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getLastRunAt()
    {
        return $this->lastRunAt;
    }

    /**
     * @param mixed $lastRunAt
     */
    public function setLastRunAt($lastRunAt)
    {
        $this->lastRunAt = $lastRunAt;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * @param mixed $enabled
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function enable()
    {
        $this->setEnabled(true);
    }

    public function disable()
    {
        $this->setEnabled(false);
    }
}

src/VR/AppBundle/Form/ProcessScheduleType.php
<?php

namespace VR\AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use VR\AppBundle\Plugin\PluginManager;

/**
 * Class ProcessScheduleType
 *
 * @package VR\AppBundle\Form
 *
 * @author Michał Jabłoński <mjapko@gmail.com>
 */
class ProcessScheduleType extends AbstractType
{
    /** @var PluginManager */
    protected $pluginManager;

    public function __construct($pluginManager)
    {
        $this->pluginManager = $pluginManager;
    }

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
            ->add('minute', 'text', [
                'required' => false
            ])
            ->add('hour', 'text', [
                'required' => false
            ])
            ->add('dayOfMonth', 'text', [
                'required' => false
            ])
            ->add('month', 'text', [
                'required' => false
            ])
            ->add('dayOfWeek', 'text', [
                'required' => false
            ])
            ->add('type', 'choice', [
                'choices' => [
                    'Collectors' => $this->pluginManager->getCollectorsRunModesList(),
                    'Workers' => $this->pluginManager->getWorkersRunModesList()
                ]
            ])
            ->add('parameters', 'textarea', [
                'required' => false
            ])
            ->add('description', 'textarea', [
                'required' => false
            ])
            ->add('enabled', 'checkbox', [
                'required' => false
            ])
        ;
	}

	public function getName()
	{
		return 'process_schedule';
	}
}

src/VR/AppBundle/Controller/ProcessScheduleController.php
<?php

namespace VR\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use VR\AppBundle\Entity\ProcessSchedule;
use VR\AppBundle\Form\ProcessScheduleType;
use VR\AppBundle\Plugin\PluginManager;

/**
 * @author Michał Jabłoński <mjapko@gmail.com>
 * @author Andrzej Prusinowski <andrzej@avris.it>
 *
 * @Route("/schedules")
 */
class ProcessScheduleController extends Controller
{
    /**
     * @Route("/", name="process_schedule_list")
     */
    public function listAction()
    {
        $em = $this->getDoctrine()->getManager();

        $processSchedules = $em->getRepository('VRAppBundle:ProcessSchedule')->findAll();

        return $this->render('VRAppBundle:ProcessSchedule:list.html.twig', array(
            'processSchedules' => $processSchedules
        ));
    }

    /**
     * @Route("/new", name="process_schedule_new")
     */
    public function newAction(Request $request)
    {
        $pluginManager = $this->get('vr.plugin_manager');

        $form = $this->createForm(new ProcessScheduleType($pluginManager), new ProcessSchedule());

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $processSchedule = $form->getData();
            $em->persist($processSchedule);
            $em->flush();

            return $this->redirectToRoute('process_schedule_list');
        }

        return $this->render('VRAppBundle:ProcessSchedule:new.html.twig', array(
            'form' => $form->createView(),
            'parameters' => $pluginManager->getAllPluginsParameters(),
        ));
	}

    /**
     * @Route("/edit/{id}", name="process_schedule_edit")
     */
    public function editAction(Request $request, ProcessSchedule $processSchedule)
    {
        $pluginManager = $this->get('vr.plugin_manager');

        $form = $this->createForm(new ProcessScheduleType($pluginManager), $processSchedule);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $processSchedule = $form->getData();
            $em->persist($processSchedule);
            $em->flush();

            return $this->redirectToRoute('process_schedule_list');
        }

        return $this->render('VRAppBundle:ProcessSchedule:edit.html.twig', array(
            'form' => $form->createView(),
            'parameters' => $pluginManager->getAllPluginsParameters(),
        ));
    }

    /**
     * @Route("/delete/{id}", name="process_schedule_delete")
     */
    public function deleteAction(Request $request, ProcessSchedule $processSchedule)
    {
        $em = $this->getDoctrine()->getManager();
        
        $em->remove($processSchedule);
        $em->flush();

        $this->get('session')->getFlashBag()->add('success', 'Scheduled process successfully removed.');
        
        return $this->redirectToRoute('process_schedule_list');
    }

    /**
     * @Route("/enable/{id}", name="process_schedule_enable")
     */
    public function enableAction(Request $request, ProcessSchedule $processSchedule)
    {
        $em = $this->getDoctrine()->getManager();

        $processSchedule->enable();
        $em->persist($processSchedule);
        $em->flush();

        $this->get('session')->getFlashBag()->add('success', 'Scheduled process successfully enabled.');

        return $this->redirectToRoute('process_schedule_list');
    }

    /**
     * @Route("/disable/{id}", name="process_schedule_disable")
     */
    public function disableAction(Request $request, ProcessSchedule $processSchedule)
    {
        $em = $this->getDoctrine()->getManager();

        $processSchedule->disable();
        $em->persist($processSchedule);
        $em->flush();

        $this->get('session')->getFlashBag()->add('success', 'Scheduled process successfully disabled.');

        return $this->redirectToRoute('process_schedule_list');
    }

    /**
     * @Route("/run/{id}", name="process_schedule_run")
     */
    public function runAction(ProcessSchedule $scheduledProcess)
    {
        $em = $this->getDoctrine()->getManager();

        $scheduledProcess->setLastRunAt(new \DateTime());
        $em->persist($scheduledProcess);
        $em->flush();

        $this->get('vr.plugin_manager')->runScheduledProcess($scheduledProcess);

        $this->get('session')->getFlashBag()->add('success', 'SQL has been executed.');

        return $this->redirectToRoute('process_schedule_list');
    }
}

src/VR/AppBundle/Resources/views/ProcessSchedule/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Edit scheduled process</h1>

    <div class="row">
        <div class="col-md-12">
            <form action="" method="post" class="form-horizontal">
                {% include 'VRAppBundle:ProcessSchedule:form.html.twig' %}

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

src/VR/AppBundle/Resources/views/ProcessSchedule/form.html.twig
{{ form_errors(form) }}

<div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-7">
        {{ form_widget(form.enabled) }}
        {{ form_errors(form.enabled) }}
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-7">
        <table class="table">
            <tr>
                <td>Min</td>
                <td>Hour</td>
                <td>Day of Month</td>
                <td>Month</td>
                <td>Day of Week</td>
            </tr>
            <tr>
                <td>{{ form_widget(form.minute) }}</td>
                <td>{{ form_widget(form.hour) }}</td>
                <td>{{ form_widget(form.dayOfMonth) }}</td>
                <td>{{ form_widget(form.month) }}</td>
                <td>{{ form_widget(form.dayOfWeek) }}</td>
            </tr>
            <tr>
                <td colspan="5">
                    <div>{{ form_errors(form.minute) }}</div>
                    <div>{{ form_errors(form.hour) }}</div>
                    <div>{{ form_errors(form.dayOfMonth) }}</div>
                    <div>{{ form_errors(form.month) }}</div>
                    <div>{{ form_errors(form.dayOfWeek) }}</div>
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Type</label>
    <div class="col-sm-7">
        {{ form_widget(form.type) }}
        {{ form_errors(form.type) }}
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Description</label>
    <div class="col-sm-7">
        {{ form_widget(form.description) }}
        {{ form_errors(form.description) }}
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Parameters</label>
    <div class="col-sm-7">
        <div class="alert alert-info">
            <div id="parametersHelper1"></div>
            <div id="parametersHelper2"></div>
        </div>
        {{ form_widget(form.parameters, {attr: {rows: 15}}) }}
        {{ form_errors(form.parameters) }}
        <div id="parameters_editor"></div>
    </div>
</div>

{{ form_rest(form) }}

<script src="{{ asset('ace/ace.js') }}" type="text/javascript" charset="utf-8"></script>
<script>var parameters = {{ parameters|json_encode|raw }};</script>

src/VR/AppBundle/Resources/views/ProcessSchedule/list.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Schedules</h1>

    <p>
        <a href="{{ path('process_schedule_new') }}" class="btn btn-success">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create new
        </a>
    </p>

    <div class="well row">
        <div class="col-lg-6">
            <p>
                Cron time definition consists of five values:
                <strong>minutes, hours, day of month, month, day of week</strong>
                (0 for Sunday to 6 for Saturday)
            </p>
            <p>
                <strong>Asterisk *</strong> means: every possible value of given unit
            </p>
            <p>
                <strong>Slash /</strong> lets you select from a range of numbers
                those divisible by some number, e.g.: */3 will run every tree minutes: 0, 3, 6, 9...
            </p>
            <p>
                <strong>Dash -</strong> creates a range of numbers,
                e.g. 7-19 means everything between 7 and 19 (inclusively)
            </p>
            <p>
                <strong>Comma ,</strong> creates a set of numbers, eg. 3,7,15 will run on 3 and 7 and 15.
            </p>
        </div>
        <div class="col-lg-6">
            <h4>Examples</h4>
            <p><strong>* * * * *</strong> - every minute</p>
            <p><strong>*/2 * * * *</strong> - every even minute</p>
            <p><strong>0 9-17 * * *</strong> - on whole hours from nine to five</p>
            <p><strong>0 8-16/2 * * 1</strong> - on 8, 10, 12, 14 and 16 o' clock, but just on mondays</p>
            <p><strong>0 8,10,12,14,16 * * 1</strong> - same as above</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            <table class="table table-striped table-bordered">
                <thead>
                <th>
                    ID
                </th>
                <th>
                    Cron
                </th>
                <th>
                    Type
                </th>
                <th>
                    Description
                </th>
                <th>
                    Last run at
                </th>
                <th></th>
                </thead>
                <tbody>
                {% for schedule in processSchedules %}
                    <tr>
                        <td>
                            {{ schedule.id }}
                        </td>
                        <td class="nowrap">
                            {{ schedule.time }}
                        </td>
                        <td>
                            {{ schedule.typeName }}
                        </td>
                        <td style="max-width: 350px">
                            {{ schedule.description }}
                        </td>
                        <td class="nowrap">
                            {% if schedule.lastRunAt %}
                                {{ schedule.lastRunAt|date('Y-m-d H:i:s') }}
                            {% endif %}
                        </td>
                        <td class="table-actions">
                            {% if schedule.enabled %}
                                <a href="{{ path('process_schedule_disable', {id: schedule.id}) }}" class="btn btn-warning btn-xs" title="Disable">
                                    <span class="glyphicon glyphicon-stop" aria-hidden="true"></span>
                                </a>
                            {% else %}
                                <a href="{{ path('process_schedule_enable', {id: schedule.id}) }}" class="btn btn-success btn-xs" title="Enable">
                                    <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
                                </a>
                            {% endif %}

                            <a href="{{ path('process_schedule_edit', {id: schedule.id}) }}" class="btn btn-default btn-xs">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                            </a>

                            <a href="{{ path('process_schedule_delete', {id: schedule.id}) }}" class="btn btn-danger btn-xs confirm" data-message="Are you sure?">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
                            </a>

                            {% if schedule.type == 'plugin.collector.sql.main' %}
                                <a href="{{ path('process_schedule_run', {id: schedule.id}) }}" class="btn btn-info btn-xs" title="Run now">
                                    <span class="glyphicon glyphicon-play" aria-hidden="true"></span> Run now
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

src/VR/AppBundle/Resources/views/ProcessSchedule/new.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Add scheduled process</h1>

    <div class="row">
        <div class="col-md-12">
            <form action="" method="post" class="form-horizontal">
                {% include 'VRAppBundle:ProcessSchedule:form.html.twig' %}

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}